In [6]:
import sys
import os
sys.path.insert(0, os.path.abspath("../.."))
from src.pipeline import run_etl
from src.pipeline import DOMINIOS
from src.modeling import seed, scoring, train_model

In [8]:
df_tabla_0_imp, df_tabla_1_imp,df_mean, df_median = run_etl("../../.env")

Descargando datos desde GitHub...
Hojas cargadas: 125
Tabla 0 (escolaridad baja) : 36
Tabla 1 (escolaridad alta) : 81
No determinadas            : 8
df_tabla_0 crudo : (36, 32)
df_tabla_1 crudo : (81, 29)

 Imputando nulos...
--- Perfil nulos Tabla 0 ---
                                         nulos  %_nulos dtype  n_unicos
fluidez_verbal_semantica                    23    63.89   str         4
matrices                                    12    33.33   str         4
imagenes_sobrepuestas                       11    30.56   str         3
stroop_interferencia                         9    25.00   str         4
material_verbal_complejo                     6    16.67   str         3
denominacion                                 5    13.89   str         1
stroop_palabra                               4    11.11   str         4
stroop_color                                 4    11.11   str         4
atencion_sostenida_visual                    4    11.11   str         4
evocacion_diferida                           4    11.11   str         4
memoria_de_trabajo_digitos_secuenciales      3     8.33   str         2
comprension_abstraccion                      3     8.33   str         4
semejanzas                                   3     8.33   str         4
comprension_de_ordenes                       2     5.56   str         3
copia_de_figura                              2     5.56   str         4
reconocimiento                               2     5.56   str         2
recuerdo_inmediato_lista_b                   2     5.56   str         2
recuerdo_libre_a_corto_plazo                 2     5.56   str         2
recuerdo_inmediato_lista_a                   2     5.56   str         2
evocacion_inmediata_lista_a                  2     5.56   str         2
recuerdo_libre_a_largo_plazo                 2     5.56   str         2
atencion_dividida_visual                     1     2.78   str         2
atencion_selectiva_visual                    1     2.78   str         2
atencion_sostenida_auditiva                  1     2.78   str         3
tiempo                                       1     2.78   str         3
persona                                      1     2.78   str         1
espacio                                      1     2.78   str         2
memoria_de_trabajo_digitos_inversos          1     2.78   str         3

--- Perfil nulos Tabla 1 ---
                                   nulos  %_nulos dtype  n_unicos
comprension_de_ordenes                32    39.51   str         3
memoria_logica_promedio_historias     30    37.04   str         4
gestos_simbolicos                     24    29.63   str         3
caras_codificacion                    15    18.52   str         3
reconocimiento_caras                  14    17.28   str         3
imagenes_sobrepuestas                 11    13.58   str         3
evocacion_figura_semicompleja         10    12.35   str         4
material_verbal_complejo              10    12.35   str         3
semejanzas                             9    11.11   str         3
memoria_verbal_reconocimiento          7     8.64   str         5
curva_de_memoria_volumen_promedio      7     8.64   str         4
memoria_verbal_espontanea_total        7     8.64   str         4
memoria_verbal_claves_total            7     8.64   str         4
deteccion_visual                       6     7.41   str         4
denominacion                           6     7.41   str         3
fluidez_no_verbal                      6     7.41   str         4
copia_de_figura                        4     4.94   str         4
retencion_digitos_regresion            4     4.94   str         4
series_sucesivas                       3     3.70   str         3
espacio                                3     3.70   str         2
digitos_en_progresion                  3     3.70   str         4
tiempo                                 3     3.70   str         3
persona                                3     3.70   str         2
fluidez_verbal_fonologica              3     3.70   str         4
fluidez_verbal_semantica               3     3.70   str         4

df_tabla_0_imp : (36, 60)
df_tabla_1_imp : (81, 54)

df_mean   listo: (117, 19)
df_median listo: (117, 19)

    Nulos en df_mean:
nivel_estudio       0
dc                  0
age_num             0
n_orientacion       0
orientacion         0
n_atencion          0
atencion            0
n_lenguaje          0
lenguaje            0
n_memoria_verbal    0
memoria_verbal      0
n_memoria_visual    0
memoria_visual      0
n_gnosias           0
gnosias             7
n_praxis            0
praxis              0
n_ejecutivas        0
ejecutivas          0
dtype: int64

    Distribución clínica:
      Control  : 27
      DCL      : 58
      Demencia : 32
      Total    : 117

    Pruebas por dominio (media de n_{dominio} en df_mean):
      n_orientacion         : 3.0
      n_atencion            : 3.3
      n_lenguaje            : 3.7
      n_memoria_verbal      : 5.0
      n_memoria_visual      : 2.4
      n_gnosias             : 1.1
      n_praxis              : 1.7
      n_ejecutivas          : 4.6

nivel_estudio       0
dc                  0
age_num             0
n_orientacion       0
orientacion         0
n_atencion          0
atencion            0
n_lenguaje          0
lenguaje            0
n_memoria_verbal    0
memoria_verbal      0
n_memoria_visual    0
memoria_visual      0
n_gnosias           0
gnosias             7
n_praxis            0
praxis              0
n_ejecutivas        0
ejecutivas          0
dtype: int64

In [11]:
df_mean.describe().T

,count,mean,std,min,25%,50%,75%,max
nivel_estudio,117.0,0.692308,0.463524,0.000000,0.000000,1.000000,1.00,1.000000
dc,117.0,1.042735,0.711884,0.000000,1.000000,1.000000,2.00,2.000000
age_num,117.0,70.743590,9.698164,51.000000,65.000000,71.000000,77.00,96.000000
n_orientacion,117.0,3.000000,0.000000,3.000000,3.000000,3.000000,3.00,3.000000
orientacion,117.0,2.849003,0.935154,1.000000,2.333333,3.000000,4.00,4.000000
n_atencion,117.0,3.307692,0.463524,3.000000,3.000000,3.000000,4.00,4.000000
atencion,117.0,2.817664,0.378722,1.666667,2.666667,3.000000,3.00,3.666667
n_lenguaje,117.0,3.726496,0.447675,3.000000,3.000000,4.000000,4.00,4.000000
lenguaje,117.0,3.341168,0.547874,2.000000,3.000000,3.500000,3.75,4.000000
n_memoria_verbal,117.0,5.042735,0.770056,3.000000,4.000000,5.000000,6.00,6.000000
memoria_verbal,117.0,2.578632,0.436844,1.000000,2.250000,2.600000,3.00,4.000000
n_memoria_visual,117.0,2.384615,0.927047,1.000000,1.000000,3.000000,3.00,3.000000
memoria_visual,117.0,2.740741,0.424605,1.000000,2.666667,2.666667,3.00,4.000000
n_gnosias,117.0,1.111111,0.469368,0.000000,1.000000,1.000000,1.00,2.000000
gnosias,110.0,3.472727,0.741423,2.000000,3.000000,4.000000,4.00,4.000000
n_praxis,117.0,1.692308,0.463524,1.000000,1.000000,2.000000,2.00,2.000000
praxis,117.0,3.089744,0.641978,1.000000,2.500000,3.000000,3.50,4.000000
n_ejecutivas,117.0,4.623932,1.023234,4.000000,4.000000,4.000000,5.00,7.000000
ejecutivas,117.0,2.621347,0.492163,1.250000,2.250000,2.750000,3.00,3.750000

In [12]:
df_median.describe().T

                  count       mean       std   min   25%   50%   75%   max
nivel_estudio     117.0   0.692308  0.463524   0.0   0.0   1.0   1.0   1.0
dc                117.0   1.042735  0.711884   0.0   1.0   1.0   2.0   2.0
age_num           117.0  70.743590  9.698164  51.0  65.0  71.0  77.0  96.0
n_orientacion     117.0   3.000000  0.000000   3.0   3.0   3.0   3.0   3.0
orientacion       117.0   2.948718  0.998673   1.0   3.0   3.0   4.0   4.0
n_atencion        117.0   3.307692  0.463524   3.0   3.0   3.0   4.0   4.0
atencion          117.0   2.876068  0.382291   1.0   3.0   3.0   3.0   4.0
n_lenguaje        117.0   3.726496  0.447675   3.0   3.0   4.0   4.0   4.0
lenguaje          117.0   3.538462  0.698378   2.0   3.0   4.0   4.0   4.0
n_memoria_verbal  117.0   5.042735  0.770056   3.0   4.0   5.0   6.0   6.0
memoria_verbal    117.0   2.589744  0.498339   1.0   2.0   3.0   3.0   4.0
n_memoria_visual  117.0   2.384615  0.927047   1.0   1.0   3.0   3.0   3.0
memoria_visual    117.0   2.863248  0.471717   1.0   3.0   3.0   3.0   4.0
n_gnosias         117.0   1.111111  0.469368   0.0   1.0   1.0   1.0   2.0
gnosias           110.0   3.472727  0.741423   2.0   3.0   4.0   4.0   4.0
n_praxis          117.0   1.692308  0.463524   1.0   1.0   2.0   2.0   2.0
praxis            117.0   3.089744  0.641978   1.0   2.5   3.0   3.5   4.0
n_ejecutivas      117.0   4.623932  1.023234   4.0   4.0   4.0   5.0   7.0
ejecutivas        117.0   2.679487  0.551102   1.0   2.5   3.0   3.0   4.0

In [14]:
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedKFold, cross_validate, cross_val_predict, GridSearchCV, RepeatedStratifiedKFold

score = train_model(SVC(kernel='linear', class_weight='balanced', C=0.1, gamma='scale', random_state=seed), df_mean.drop(columns=['dc']), df_mean['dc'], cv=RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=seed))

In [15]:
print(f'score f1 macro: {score['train_f1_macro'].mean()}')

score f1 macro: 0.8570750913577683